puts "The students of the villain academy"
puts "------------------"
puts "Dr. Hannibal Lector"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The wicked witch of the wild west"
puts "Terminator"
puts "Freddie Kruger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"
